// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOh7cfrNXuKaXyL3wIdG8IA0apKAg2a2w',
    appId: '1:273441332116:web:bc8f5b9532da02fc664d81',
    messagingSenderId: '273441332116',
    projectId: 'dioryproject-ef767',
    authDomain: 'dioryproject-ef767.firebaseapp.com',
    storageBucket: 'dioryproject-ef767.appspot.com',
    measurementId: 'G-TV1EFR9MP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NYfgOzcIjTWdozEoTGgXNMAnjEiCk6k',
    appId: '1:273441332116:android:0f04c0a998d3410a664d81',
    messagingSenderId: '273441332116',
    projectId: 'dioryproject-ef767',
    storageBucket: 'dioryproject-ef767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrb8zzOlC-ZX3XoCQJMv19CKKgTTRivEE',
    appId: '1:273441332116:ios:6734d525bbdb2a66664d81',
    messagingSenderId: '273441332116',
    projectId: 'dioryproject-ef767',
    storageBucket: 'dioryproject-ef767.appspot.com',
    iosClientId: '273441332116-3b6tg9811ep5dts8d8op3046j71kaf98.apps.googleusercontent.com',
    iosBundleId: 'com.example.diory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrb8zzOlC-ZX3XoCQJMv19CKKgTTRivEE',
    appId: '1:273441332116:ios:6734d525bbdb2a66664d81',
    messagingSenderId: '273441332116',
    projectId: 'dioryproject-ef767',
    storageBucket: 'dioryproject-ef767.appspot.com',
    iosClientId: '273441332116-3b6tg9811ep5dts8d8op3046j71kaf98.apps.googleusercontent.com',
    iosBundleId: 'com.example.diory',
  );
}
